In [205]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # for data visualization
import seaborn as sns # for statistical data visualization
%matplotlib inline
from sklearn.metrics import confusion_matrix

import os

df = pd.read_csv("dataset/depressionDataset.csv")

In [204]:
# view dimensions of dataset

df.shape

(16150, 11)

In [172]:
# let's preview the dataset

df.head()

id   q1   q2   q3   q4   q5   q6   q7   q8   q9  q10  score  class  \
0  1.0  3.0  2.0  2.0  2.0  3.0  0.0  0.0  0.0  0.0  3.0   15.0    3.0   
1  2.0  0.0  3.0  0.0  0.0  0.0  3.0  0.0  0.0  0.0  0.0    6.0    1.0   
2  3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    0.0    0.0   
3  4.0  2.0  1.0  1.0  2.0  0.0  0.0  2.0  3.0  0.0  3.0   14.0    2.0   
4  5.0  1.0  3.0  1.0  1.0  2.0  1.0  2.0  3.0  0.0  1.0   15.0    3.0   

                  time period.name           start.time  
0  2017-01-22 20:11:59     evening  2017-01-09 07:22:37  
1  2017-02-08 22:53:06     evening  2017-01-09 07:22:37  
2  2017-02-08 08:00:46     morning  2017-01-09 07:22:37  
3  2017-01-22 14:01:25      midday  2017-01-09 07:22:37  
4  2017-01-21 15:37:24      midday  2017-01-09 07:22:37

In [173]:
# view the column names of the dataframe

col_names = df.columns

col_names

Index(['id', 'q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10',
       'score', 'class', 'time', 'period.name', 'start.time'],
      dtype='object')

In [174]:
df.drop(['id','score','time','period.name','start.time'], axis=1, inplace=True)

In [175]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16150 entries, 0 to 16149
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   q1      15923 non-null  float64
 1   q2      15923 non-null  float64
 2   q3      15923 non-null  float64
 3   q4      15923 non-null  float64
 4   q5      15923 non-null  float64
 5   q6      15923 non-null  float64
 6   q7      15923 non-null  float64
 7   q8      15923 non-null  float64
 8   q9      15923 non-null  float64
 9   q10     15923 non-null  float64
 10  class   15923 non-null  float64
dtypes: float64(11)
memory usage: 1.4 MB


In [176]:
# view the column names of the dataframe again

col_names = df.columns

col_names

Index(['q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10', 'class'], dtype='object')

In [177]:
# check distribution of target_class column

df['class'].value_counts()

3.0    3635
2.0    3585
0.0    3018
1.0    2902
4.0    2783
Name: class, dtype: int64

In [178]:
# view the percentage distribution of target_class column

df['class'].value_counts()/np.float64(len(df))

3.0    0.225077
2.0    0.221981
0.0    0.186873
1.0    0.179690
4.0    0.172322
Name: class, dtype: float64

In [179]:
# check for missing values in variables

df.isnull().sum()

q1       227
q2       227
q3       227
q4       227
q5       227
q6       227
q7       227
q8       227
q9       227
q10      227
class    227
dtype: int64

In [180]:
df['q1'] = df['q1'].fillna(df['q1'].mode()[0])
df['q2'] = df['q2'].fillna(df['q2'].mode()[0])
df['q3'] = df['q3'].fillna(df['q3'].mode()[0])
df['q4'] = df['q4'].fillna(df['q4'].mode()[0])
df['q5'] = df['q5'].fillna(df['q5'].mode()[0])
df['q6'] = df['q6'].fillna(df['q6'].mode()[0])
df['q7'] = df['q7'].fillna(df['q7'].mode()[0])
df['q8'] = df['q8'].fillna(df['q8'].mode()[0])
df['q9'] = df['q9'].fillna(df['q9'].mode()[0])
df['q10'] = df['q10'].fillna(df['q10'].mode()[0])
df['class'] = df['class'].fillna(df['class'].mode()[0])

In [181]:
# check for missing values in variables

df.isnull().sum()

q1       0
q2       0
q3       0
q4       0
q5       0
q6       0
q7       0
q8       0
q9       0
q10      0
class    0
dtype: int64

In [182]:
# view summary statistics in numerical variables

round(df.describe(),2)

q1        q2        q3        q4        q5        q6        q7  \
count  16150.00  16150.00  16150.00  16150.00  16150.00  16150.00  16150.00   
mean       1.07      1.15      1.21      1.24      1.11      1.30      1.12   
std        1.13      1.13      1.19      1.19      1.09      1.12      1.09   
min        0.00      0.00      0.00      0.00      0.00      0.00      0.00   
25%        0.00      0.00      0.00      0.00      0.00      0.00      0.00   
50%        1.00      1.00      1.00      1.00      1.00      1.00      1.00   
75%        2.00      2.00      2.00      2.00      2.00      2.00      2.00   
max        3.00      3.00      3.00      3.00      3.00      3.00      3.00   

            q8        q9       q10     class  
count  16150.0  16150.00  16150.00  16150.00  
mean       1.2      1.22      1.20      2.03  
std        1.2      1.25      1.21      1.36  
min        0.0      0.00      0.00      0.00  
25%        0.0      0.00      0.00      1.00  
50%        1.0      1.00      1.00      2.00  
75%        2.0      3.00      2.00      3.00  
max        3.0      3.00      3.00      4.00

In [183]:
X = df.drop(['class'], axis=1)

y = df['class']

In [184]:
# split X and y into training and testing sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 24)

In [185]:
# check the shape of X_train and X_test

X_train.shape, X_test.shape

((9690, 10), (6460, 10))

In [186]:
# import SVC classifier
from sklearn.svm import SVC


# import metrics to compute accuracy
from sklearn.metrics import accuracy_score


# instantiate classifier with default hyperparameters
svc=SVC() 


# fit classifier to training set
svc.fit(X_train,y_train)


# make predictions on test set
y_pred=svc.predict(X_test)


# compute and print accuracy score
print('Model accuracy score with default hyperparameters: {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with default hyperparameters: 0.9393


In [207]:
class Model2:
# instantiate classifier with linear kernel and C=1.0
    linear_svc=SVC(kernel='linear', C=1.0) 


# fit classifier to training set
    linear_svc.fit(X_train,y_train)


# make predictions on test set
    y_pred_test=linear_svc.predict(X_test)


# compute and print accuracy score
    print('Model accuracy score with linear kernel and C=1.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred_test)))

Model accuracy score with linear kernel and C=1.0 : 0.9440


In [188]:
y_pred_train = linear_svc.predict(X_train)

y_pred_train

array([1., 1., 2., ..., 3., 2., 1.])

In [189]:
print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))

Training-set accuracy score: 0.9518


In [190]:
# print the scores on training and test set

print('Training set score: {:.4f}'.format(linear_svc.score(X_train, y_train)))

print('Test set score: {:.4f}'.format(linear_svc.score(X_test, y_test)))

Training set score: 0.9518
Test set score: 0.9440


In [191]:
# check class distribution in test set

y_test.value_counts()

3.0    1556
2.0    1439
0.0    1188
1.0    1184
4.0    1093
Name: class, dtype: int64

In [192]:
# check null accuracy score

null_accuracy = (760/(760+716+623+584+547))

print('Null accuracy score: {0:0.4f}'. format(null_accuracy))

Null accuracy score: 0.2353


In [193]:
# instantiate classifier with polynomial kernel and C=1.0
poly_svc=SVC(kernel='poly', C=1.0) 


# fit classifier to training set
poly_svc.fit(X_train,y_train)


# make predictions on test set
y_pred=poly_svc.predict(X_test)


# compute and print accuracy score
print('Model accuracy score with polynomial kernel and C=1.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with polynomial kernel and C=1.0 : 0.9341


In [194]:
# Print the Confusion Matrix and slice it into four pieces

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_test)

print('Confusion matrix\n\n', cm)

print('\nTrue Positives(TP) = ', cm[0,0])

print('\nTrue Negatives(TN) = ', cm[1,1])

print('\nFalse Positives(FP) = ', cm[0,1])

print('\nFalse Negatives(FN) = ', cm[1,0])

Confusion matrix

 [[1186    2    0    0    0]
 [   2 1182    0    0    0]
 [   0   40 1358   41    0]
 [  96    0  118 1310   32]
 [   0    0    0   31 1062]]

True Positives(TP) =  1186

True Negatives(TN) =  1182

False Positives(FP) =  2

False Negatives(FN) =  2


In [195]:
TP = cm[0,0]
TN = cm[1,1]
FP = cm[0,1]
FN = cm[1,0]

In [196]:
# print classification accuracy

classification_accuracy = (TP + TN) / float(TP + TN + FP + FN)

print('Classification accuracy : {0:0.4f}'.format(classification_accuracy))

Classification accuracy : 0.9983


In [197]:
# print classification error

classification_error = (FP + FN) / float(TP + TN + FP + FN)

print('Classification error : {0:0.4f}'.format(classification_error))

Classification error : 0.0017


In [198]:
# print precision score

precision = TP / float(TP + FP)


print('Precision : {0:0.4f}'.format(precision))

Precision : 0.9983


In [199]:
recall = TP / float(TP + FN)

print('Recall or Sensitivity : {0:0.4f}'.format(recall))

true_positive_rate = TP / float(TP + FN)


print('True Positive Rate : {0:0.4f}'.format(true_positive_rate))

false_positive_rate = FP / float(FP + TN)


print('False Positive Rate : {0:0.4f}'.format(false_positive_rate))

specificity = TN / (TN + FP)

print('Specificity : {0:0.4f}'.format(specificity))

Recall or Sensitivity : 0.9983
True Positive Rate : 0.9983
False Positive Rate : 0.0017
Specificity : 0.9983
